(() => {
  const workspace = document.querySelector('.workspace');
  const tabs = [...document.querySelectorAll('.tab')];
  if (!workspace || tabs.length < 3) return;
  const canvas = workspace.querySelector('.canvas');
  if (!canvas) return;
  const view = document.createElement('section'); view.className = 'module-view'; view.setAttribute('aria-live', 'polite'); canvas.appendChild(view);
  const rows = [['MG Road','Congested','94%','AI active'],['Connaught Place','Optimal','61%','AI active'],['Dhaula Kuan','Moderate','73%','Review'],['India Gate','Optimal','48%','AI active']];
  const render = (name) => { const analytics = name === 'Analytics'; const flow = name === 'Signal flow'; view.innerHTML = `<div class="module-view-head"><div><h2>${analytics ? 'Network analytics' : flow ? 'Signal flow' : 'Command overview'}</h2><p>${analytics ? 'Performance across the active emergency network.' : flow ? 'Signal phases and corridor readiness by junction.' : 'A concise operational view of the traffic-response system.'}</p></div><button class="module-view-close" type="button">Back to live map</button></div><div class="overview-grid"><article class="overview-card"><span>Network health</span><strong>96%</strong><small>+4.2% vs baseline</small></article><article class="overview-card"><span>Active junctions</span><strong>06</strong><small>All reporting</small></article><article class="overview-card"><span>Avg response</span><strong>08:42</strong><small>03:18 saved by AI</small></article><article class="overview-card"><span>Corridor status</span><strong>${flow ? 'READY' : 'LIVE'}</strong><small>${analytics ? '13.64% faster than fixed' : 'Emergency priority available'}</small></article></div><div class="module-table"><h3>${analytics ? 'Performance by junction' : flow ? 'Current signal phases' : 'Operational junction overview'}</h3>${rows.map((row, index) => `<div class="module-row"><b>${row[0]}</b><span>${flow ? `${18 + index * 4}s green` : row[1]}</span><span>${analytics ? `${row[2]} load` : `Offset ${index * 16}s`}</span><span class="module-status ${row[1] === 'Moderate' ? 'warn' : ''}">${row[3]}</span></div>`).join('')}</div>`; view.querySelector('.module-view-close').onclick = () => setActive(0); };
  const setActive = (index) => { tabs.forEach((tab, i) => tab.classList.toggle('active', i === index)); const map = canvas.querySelector('.map-wrap'); const start = canvas.querySelector('.floating-start'); if (index === 0) { view.classList.remove('active'); map.style.display = ''; start.style.display = ''; } else { map.style.display = 'none'; start.style.display = 'none'; view.classList.add('active'); render(tabs[index].textContent.trim()); } };
  tabs.forEach((tab, index) => { tab.onclick = () => setActive(index); });
})();
