const nodes = [{ name: "Connaught Place Outer Circle", pos: [28.6328,77.2197], traffic: 68, tone: "cyan", counts: [65,42,18,9] },{ name: "Dhaula Kuan Interchange", pos: [28.5918,77.1616], traffic: 82, tone: "yellow", counts: [78,56,44,32] },{ name: "Mukarba Chowk Flyover", pos: [28.7369,77.161], traffic: 94, tone: "red", counts: [92,74,61,48] },{ name: "AIIMS Trauma Center", pos: [28.568,77.211], traffic: 28, tone: "cyan", counts: [18,14,8,4] },{ name: "Ashram Chowk", pos: [28.571,77.258], traffic: 55, tone: "yellow", counts: [51,36,26,14] },{ name: "Punjabi Bagh", pos: [28.6675,77.125], traffic: 47, tone: "cyan", counts: [42,30,22,11] }];
let map; let dispatchMode = false; let dispatchStep = 0; let startPoint; let routeLayer; let evMarker;
const $ = (id) => document.getElementById(id);

function initMap(){ map=L.map("map",{zoomControl:false}).setView([28.635,77.205],11); L.control.zoom({position:"bottomright"}).addTo(map); L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{attribution:"© OpenStreetMap © CARTO"}).addTo(map); nodes.forEach((node,index)=>{const icon=L.divIcon({className:`junction-marker ${node.tone}`,html:`<span>${24-index*3}s</span>`,iconSize:[38,38],iconAnchor:[19,19]}); const marker=L.marker(node.pos,{icon}).addTo(map).bindTooltip(node.name,{direction:"top"}); marker.on("click",()=>selectNode(node));}); map.on("click",(event)=>{if(!dispatchMode)return; if(dispatchStep===1){startPoint=event.latlng;dispatchStep=2;$("dispatchInstruction").textContent="Start set. Click on map to set EMERGENCY DESTINATION";L.circleMarker(startPoint,{radius:8,color:"#ff0055",fillColor:"#ff0055",fillOpacity:1}).addTo(map);return;} if(dispatchStep===2){const end=event.latlng;dispatchStep=3;dispatchMode=false;activateRoute(startPoint,end);}}); }
function selectNode(node){$("junctionName").textContent=node.name;$("junctionStatus").textContent=node.traffic>80?"HEAVY":"OPTIMIZED";$("junctionStatus").style.color=node.traffic>80?"#f7c95c":"#00f2fe";["northCount","eastCount","southCount","westCount"].forEach((id,i)=>$(id).textContent=node.counts[i]);$("mapHint").textContent=`${node.name} selected - phase detail loaded`;}
function chart(id,label,data,color){return new Chart($(id),{type:"line",data:{labels:["-60m","-45m","-30m","-15m","Now"],datasets:[{label,data,borderColor:color,backgroundColor:`${color}22`,fill:true,tension:.35,pointRadius:2,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:"#718197",font:{size:9}}},y:{grid:{color:"#223044"},ticks:{color:"#718197",font:{size:9}}}}}});}
function activateRoute(start,end){routeLayer=L.polyline([start,end],{color:"#ff0055",weight:5,dashArray:"10 8",className:"corridor-line"}).addTo(map);evMarker=L.marker(start,{icon:L.divIcon({className:"ev-marker",html:"🚑",iconSize:[28,28],iconAnchor:[14,14]})}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[55,55]});$("dispatchBadge").textContent="ACTIVE";$("dispatchBadge").classList.add("active");$("modeLabel").textContent="EMERGENCY CORRIDOR ACTIVE";$("modeLabel").style.color="#ff6a9b";$("activeCorridors").textContent="1";$("dispatchInstruction").textContent="Optimal corridor active. All-green recommendation issued for route.";$("dispatchButton").textContent="END EMERGENCY SIMULATION";$("dispatchButton").classList.add("active");}
function init(){initMap();chart("waitChart","AI wait",[39,34,29,25,22],"#00f2fe");chart("evChart","Deviation",[-18,-31,-46,-52,-61],"#ff0055");chart("co2Chart","CO2 saved",[12,24,39,51,68],"#4bd697");setInterval(()=>$("clock").textContent=new Date().toLocaleTimeString("en-IN",{hour12:false}),1000);$("dispatchButton").addEventListener("click",()=>{if($("dispatchButton").classList.contains("active")){location.reload();return;}dispatchMode=true;dispatchStep=1;$("dispatchBadge").textContent="SELECT START";$("dispatchInstruction").textContent="Click on map to set EMERGENCY START POINT";$("dispatchButton").textContent="DISPATCH MODE ACTIVE";});$("junctionSelect").addEventListener("change",(event)=>{const node=nodes.find((item)=>item.name.startsWith(event.target.value.split(" ")[0]))||nodes[0];selectNode(node);});}
init();
const themeToggle = document.getElementById("themeToggle");
if (localStorage.getItem("astrero-theme") === "light") document.body.classList.add("light-theme");
function syncThemeLabel() { themeToggle.textContent = document.body.classList.contains("light-theme") ? "Dark mode" : "Light mode"; }
syncThemeLabel();
themeToggle.addEventListener("click", () => { document.body.classList.toggle("light-theme"); localStorage.setItem("astrero-theme", document.body.classList.contains("light-theme") ? "light" : "dark"); syncThemeLabel(); });
