(() => {
  const API = location.hostname === 'localhost' || location.hostname === '127.0.0.1' ? 'http://127.0.0.1:5000/api' : '/api';
  const mapWrap = document.querySelector('.map-wrap');
  const messages = document.getElementById('messages');
  const input = document.getElementById('chatInput');
  const send = document.getElementById('send');
  if (!mapWrap || !messages || !input || !send) return;
  const fallback = [{name:'Connaught Place',vehicles:134,level:'HIGH',lat:28.6328,lng:77.2197},{name:'India Gate',vehicles:153,level:'HIGH',lat:28.6129,lng:77.2295},{name:'Dhaula Kuan',vehicles:210,level:'SEVERE',lat:28.5918,lng:77.1616}];
  const overlay = document.createElementNS('http://www.w3.org/2000/svg','svg'); overlay.classList.add('traffic-network-overlay'); overlay.setAttribute('viewBox','0 0 1000 700');
  const legend = document.createElement('div'); legend.className='traffic-map-legend'; legend.innerHTML='<b>TRAFFIC</b><br><i class="green"></i>Normal <i class="yellow"></i>Moderate<br><i class="orange"></i>Heavy <i class="red"></i>Severe';
  mapWrap.append(overlay, legend);
  let traffic = fallback; let paths=[]; let raf=0; let start=performance.now();
  const chatHead=document.querySelector('.assistant-head');
  if(chatHead){const status=document.createElement('span');status.className='assistant-live-status';status.innerHTML='<i></i> Live network context';chatHead.insertBefore(status,chatHead.querySelector('.assistant-actions'));const clear=document.createElement('button');clear.className='icon-btn';clear.setAttribute('aria-label','Clear conversation');clear.innerHTML='<i data-lucide="trash-2" width="14"></i>';clear.onclick=()=>{messages.replaceChildren();addMessage('Tarrid AI','Conversation cleared. Ask me about congestion, signal timing, emergency corridors, or network health.');if(window.lucide)lucide.createIcons();};chatHead.querySelector('.assistant-actions')?.prepend(clear);}
  const corridorLayer = window.trafficMap && L.layerGroup().addTo(window.trafficMap);
  const corridorLines = [];
  const signalMarkers = [];
  const corridors = [
    {id:'c1',name:'Ring Road Southern Arc',density:85,path:[[28.5918,77.1616],[28.5835,77.17],[28.5685,77.206],[28.5672,77.21],[28.5695,77.2435],[28.571,77.258]]},
    {id:'c2',name:'Outer Ring Road North Arc',density:78,path:[[28.7369,77.161],[28.7065,77.181],[28.685,77.21],[28.6665,77.23]]},
    {id:'c3',name:'Vikas Marg East Expressway',density:45,path:[[28.628,77.241],[28.63,77.276],[28.641,77.295],[28.6475,77.315]]},
    {id:'c4',name:'NH-48 Airport Corridor',density:32,path:[[28.549,77.121],[28.542,77.135],[28.5918,77.1616],[28.601,77.171]]},
    {id:'c5',name:'Central Janpath Line',density:60,path:[[28.6328,77.2197],[28.625,77.2185],[28.6186,77.2163],[28.6255,77.2065]]},
    {id:'c6',name:'Rohtak Road West Arterial',density:82,path:[[28.6795,77.0935],[28.6675,77.125],[28.662,77.148]]},
    {id:'c7',name:'GT Road Shahdara Arterial',density:74,path:[[28.6665,77.23],[28.669,77.268],[28.6835,77.309]]},
    {id:'c8',name:'Mathura Road South Arterial',density:58,path:[[28.571,77.258],[28.5505,77.2625],[28.535,77.275]]},
    {id:'c9',name:'Outer Ring South Arc',density:38,path:[[28.555,77.175],[28.5455,77.1925],[28.5448,77.2185],[28.5492,77.252]]},
    {id:'c10',name:'Mehrauli-Gurgaon Road',density:48,path:[[28.525,77.185],[28.5205,77.2105],[28.49,77.1]]}
  ];
  const corridorColor = density => density >= 80 ? '#d94b57' : density >= 60 ? '#d28d18' : '#20a56b';
  corridors.forEach(c => { if (!corridorLayer) return; const line=L.polyline(c.path,{color:corridorColor(c.density),weight:5,opacity:.82}); line.bindTooltip(`${c.name} · ${c.density}% load`,{sticky:true}); line.addTo(corridorLayer); corridorLines.push({line,data:c}); });
  const refreshCorridors = () => { const loads=traffic.map(item=>Number(item.vehicles)||0); const average=loads.length ? loads.reduce((sum,value)=>sum+value,0)/loads.length : 120; corridorLines.forEach(({line,data},index)=>{ const locationLoad=loads[index%Math.max(1,loads.length)] || average; const density=Math.max(20,Math.min(95,Math.round(data.density*(locationLoad/120)))); line.setStyle({color:corridorColor(density),weight:density>=75?6:5,opacity:.84}); line.setTooltipContent(`${data.name} · ${density}% live load`); }); };
  const signalPoints = [[28.6328,77.2197],[28.5918,77.1616],[28.7369,77.161],[28.6129,77.2295],[28.5697,77.326],[28.495,77.089]];
  const signalNames = ['Connaught Place','Dhaula Kuan','Mukarba Chowk','India Gate','Noida Sector 18','Cyber Hub'];
  if (window.trafficMap) signalPoints.forEach((point,index) => { const marker=L.marker(point,{icon:L.divIcon({className:'traffic-light-marker',html:`<span class="traffic-light-body"><i></i><i></i><i></i></span><b>${signalNames[index]}</b>`,iconSize:[112,42],iconAnchor:[10,21]})}).addTo(window.trafficMap); signalMarkers.push(marker); });
  const refreshSignals = () => { signalMarkers.forEach((marker,index) => { const item=traffic[index%Math.max(1,traffic.length)]||fallback[0]; const state=item.level==='SEVERE'||item.level==='HIGH'?'red':item.level==='MODERATE'?'amber':'green'; marker.getElement()?.setAttribute('data-state',state); }); };
  const levelClass = (item) => item.level.toLowerCase();
  const drawNetwork = () => {
    overlay.replaceChildren(); paths=[];
    const routes=[[120,170,430,300,760,180],[120,170,420,500,760,540],[430,300,760,180,900,350],[420,500,760,540,900,350],[430,300,420,500],[760,180,900,90,960,260],[760,540,900,620,960,470],[120,170,80,330,240,620],[420,500,300,610,120,640]];
    routes.forEach((route,index)=>{const d=`M ${route[0]} ${route[1]} C ${route[2]} ${route[3]} ${route[2]} ${route[3]} ${route[4]} ${route[5]}`; const base=document.createElementNS('http://www.w3.org/2000/svg','path');base.setAttribute('d',d);base.classList.add('traffic-road-base');overlay.appendChild(base);const road=document.createElementNS('http://www.w3.org/2000/svg','path');road.setAttribute('d',d);road.classList.add('traffic-road',levelClass(traffic[index%traffic.length]));overlay.appendChild(road);paths.push({d,level:traffic[index%traffic.length].level});});
    const emergency=document.createElementNS('http://www.w3.org/2000/svg','path'); emergency.setAttribute('d','M 120 170 C 250 215 330 265 430 300 C 545 335 640 215 760 180'); emergency.classList.add('emergency-route'); overlay.appendChild(emergency);
    const nodes=[[120,170],[430,300],[420,500],[760,180],[760,540],[900,350],[960,260],[960,470],[80,330],[120,640]];
    const junctionNames=['Connaught Place','India Gate','Dhaula Kuan','AIIMS Trauma','Moti Bagh','Safdarjung','Lajpat Nagar','Noida Sector 18','Rajouri Garden','Karol Bagh'];
    nodes.forEach((point,index)=>{const item=traffic[index%traffic.length]||fallback[index%fallback.length];const level=item.level||'MODERATE';const color=level==='SEVERE'||level==='HIGH'?'#d94b57':level==='MODERATE'?'#d28d18':'#20a56b';const signal=document.createElementNS('http://www.w3.org/2000/svg','circle');signal.setAttribute('cx',point[0]);signal.setAttribute('cy',point[1]);signal.setAttribute('r','9');signal.setAttribute('fill',color);signal.classList.add('traffic-signal');overlay.appendChild(signal);const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('x',point[0]+13);label.setAttribute('y',point[1]-8);label.classList.add('traffic-signal-label');label.textContent=`J${index+1} ${junctionNames[index]}`;overlay.appendChild(label);const meta=document.createElementNS('http://www.w3.org/2000/svg','text');meta.setAttribute('x',point[0]+13);meta.setAttribute('y',point[1]+7);meta.classList.add('traffic-signal-meta');meta.textContent=`${level} · ${item.vehicles||0} vehicles`;overlay.appendChild(meta);});
    const ambulance=document.createElementNS('http://www.w3.org/2000/svg','circle');ambulance.setAttribute('r','7');ambulance.classList.add('traffic-ambulance');ambulance.dataset.route='emergency';overlay.appendChild(ambulance);
  };
  const animate=now=>{const t=(now-start)/1000;const roadPaths=overlay.querySelectorAll('path');overlay.querySelectorAll('.traffic-vehicle,.traffic-ambulance').forEach((dot,index)=>{const p=paths[index%paths.length];const len=roadPaths[index%Math.max(1,roadPaths.length)];if(!len||!p)return;const total=len.getTotalLength();if(!Number.isFinite(total)||total<=0)return;const distance=(t*(dot.classList.contains('traffic-ambulance')?34:(p.level==='SEVERE'?18:p.level==='HIGH'?28:42))+index*75)%total;const point=len.getPointAtLength(Number.isFinite(distance)?distance:0);dot.setAttribute('cx',point.x);dot.setAttribute('cy',point.y);});raf=requestAnimationFrame(animate);};
  const addVehicles=()=>{overlay.querySelectorAll('.traffic-vehicle').forEach(x=>x.remove());for(let i=0;i<Math.min(18,traffic.reduce((n,x)=>n+Math.ceil(x.vehicles/45),0));i++){const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('r',i%7===0?'5':'3');c.classList.add('traffic-vehicle');if(i===0)c.classList.add('emergency');overlay.appendChild(c);}};
  const render=()=>{drawNetwork();addVehicles();refreshCorridors();refreshSignals();if(!raf)raf=requestAnimationFrame(animate);};
  const fetchTraffic=async()=>{try{const response=await fetch(`${API}/traffic-status?mode=ai`);if(!response.ok)throw Error('traffic unavailable');const data=await response.json();traffic=data.junctions.map(j=>{const vehicles=Object.values(j.densities||{}).reduce((a,b)=>a+Number(b),0);return {...j,vehicles,level:vehicles>=190?'SEVERE':vehicles>=130?'HIGH':vehicles>=90?'MODERATE':'LOW'};});}catch{traffic=fallback;}render();};
  const localAnswer=(text)=>{const query=text.toLowerCase();const worst=[...traffic].sort((a,b)=>(b.vehicles||0)-(a.vehicles||0))[0];const light=[...traffic].sort((a,b)=>(a.vehicles||0)-(b.vehicles||0))[0];if(/jam|traffic|congestion|heavy/.test(query))return `${worst?.name||'Dhaula Kuan'} par sabse zyada load hai (${worst?.vehicles||0} vehicles, ${worst?.level||'HIGH'}). Suggested action: emergency lane ko priority do aur nearest signals ko monitor karo.`;if(/fast|route|corridor|emergency|ambulance/.test(query))return `${light?.name||'India Gate'} corridor abhi comparatively fastest hai (${light?.vehicles||0} vehicles). Emergency routing decision-support active hai; physical signal control automatic nahi hai.`;if(/health|summary|status|network/.test(query))return `Network context: ${traffic.length} junctions monitored, highest pressure ${worst?.name||'Dhaula Kuan'} par aur best flow ${light?.name||'India Gate'} par hai. Signal decisions explain karne ke liye junction name bhejo.`;if(/signal|green|red|timing/.test(query))return `Signal timing traffic density ke basis par recommend hoti hai. Current priority ${worst?.name||'Dhaula Kuan'} ko deni chahiye; dashboard ke Signal flow tab mein timing detail dekho.`;return 'Main live traffic context dekh sakta hoon. Poocho: “kahan jam hai?”, “fastest emergency route?”, “network health”, ya “signal timing explain karo”.';};
  const addMessage=(who,text,typing=false)=>{const el=document.createElement('div');el.className=`assistant-msg ${who==='You'?'user-msg':'ai-msg'}${typing?' tarrid-typing':''}`;const name=document.createElement('b');name.textContent=who;const body=document.createElement('span');body.textContent=text;const time=document.createElement('small');time.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});el.append(name,body,time);messages.appendChild(el);messages.parentElement.scrollTop=messages.parentElement.scrollHeight;return el;};
  const ask=async()=>{const text=input.value.trim();if(!text||send.disabled)return;input.value='';send.disabled=true;addMessage('You',text);const typing=addMessage('Tarrid AI','Reviewing live junction context…',true);try{const response=await fetch(`${API}/ai/traffic`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});if(!response.ok)throw Error('assistant unavailable');const data=await response.json();typing.remove();addMessage('Tarrid AI',data.response||localAnswer(text));}catch{typing.remove();addMessage('Tarrid AI',localAnswer(text));}finally{send.disabled=false;}};
  send.onclick=ask;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask();}};document.querySelectorAll('.suggestion').forEach(button=>{button.onclick=()=>{input.value=button.textContent;ask();};});
  document.querySelectorAll('.module-card').forEach((card,index)=>card.addEventListener('click',()=>{const item=traffic[index%traffic.length];if(window.trafficMap&&item?.lat)window.trafficMap.setView([item.lat,item.lng],13,{animate:true});}));
  fetchTraffic();setInterval(fetchTraffic,5000);
})();
